### model
model_name_or_path: t3ai-org/pt-model

### method
stage: freeze
do_train: true
packing: false
train_on_prompt: true
finetuning_type: freeze
deepspeed: training/ds_z2_config.json
freeze_trainable_layers: 12
freeze_trainable_modules: all

### dataset
dataset: 137N/alpaca
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/t3ai/freeze/layer12
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
ddp_timeout: 180000000
bf16: True

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
